### ISSUE TITLE
Error despite feature working

### ISSUE THREAD

**Issue by bashbunni** [bashbunni/pjs#19]
I keep getting this error when I create a new entry, despite the new entry having no problem getting created. 

![error message](https://user-images.githubusercontent.com/15822994/170269878-7772340c-2019-4f4d-86d4-4cd3e6d48bb5.png)

**Comment by bashbunni** [comment]
This fixed itself... Terrifying

**Comment by StealthyCoder** [comment]
The only thing I can think of is that the `tea.Batch` has no guaranteed order and that whatever editor you used to edit the file with changed the location / name of that particular file. Like a vim plugin that automatically saves (renames) the file to one with `.md` at the end or something because it is markdown.
